In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction

### Creating Tensors

In [3]:
#scalr
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# no. of square brackets is the dim of that vector
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Random tensors are important beacuse the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random number -> look at data-> update random numbers

In [ ]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.4501, 0.5401, 0.9492, 0.2286],
        [0.2957, 0.5496, 0.2660, 0.8771],
        [0.6885, 0.1180, 0.1883, 0.4914]])

In [ ]:
random_tensor.ndim

2

In [ ]:
## create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))  ## height, width, colour channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
zeros=torch.zeros(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.11.0+cu128'

In [ ]:
one_to_inf=torch.arange(start=1, end=11,step=2)

In [ ]:
one_to_inf

tensor([1, 3, 5, 7, 9])

### Tensor Datatypes

**Note:** Tesnor Datatypes is one of the 3 big errors you will run into with pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                             device=None, #cpu or gpu(cuda)
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
## conversion of float32 to float16
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor , can use 'tensor.dtype
2. Tensors not right shape- to get shape from a tensor , can use tensor.shape
3. Tensors not on the right device- to get device from atensor , can use tensor.device

In [ ]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2329, 0.0115, 0.0770, 0.2616],
        [0.9481, 0.0257, 0.2243, 0.0792],
        [0.0169, 0.1557, 0.1608, 0.5935]])

In [ ]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.2329, 0.0115, 0.0770, 0.2616],
        [0.9481, 0.0257, 0.2243, 0.0792],
        [0.0169, 0.1557, 0.1608, 0.5935]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on:cpu


#### Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Substraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#substract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multipliaction in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy

1. The inner dimension must match
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

2. The resulting matrix has the shape of the outer dimension
* (2,3) @ (3,2) -> (2,2)

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.2988, 0.1595, 0.3285],
        [1.0382, 0.6847, 0.7942],
        [0.8556, 0.5215, 0.7684]])

In [ ]:
# Element wise multiplications
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix  multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix mul by hand
1*1+2*2+3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.48 ms, sys: 0 ns, total: 1.48 ms
Wall time: 3.88 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 907 µs, sys: 0 ns, total: 907 µs
Wall time: 780 µs


tensor(14)

### One of the most common errors in deep learning is shape error

In [ ]:
# Shaoes for matrix multiplication
tensor_a=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_b=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

# torch.mm(tensor_a,tensor_b) # torch.mm is the same as torch.matmul

torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shaoe issues , we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimension of a given tensor

In [ ]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, sum, mean,etc (tensor aggregation)

In [ ]:
#create tensor
x=torch.arange(0,100,10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

### torch.mean function reequires a tensor of float32 datatype to work

In [ ]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
##Finding the positional min and max-- Finding the position in tensor that haa the minimum value with argmin()-> returns index position of target tensor with minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

### Reshaping, stackcing , squezzing and unsquezzing tensors

* Reshaping- reshapes an input tensor to a defined shape
* View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combines multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze- removes all 1 dimension from a tensor
* Unsqeeze- add a 1 dimension to a target tensor
* Permute- Return a view of the input with dimension permutted(swapped) in a certain way

In [ ]:
# Create tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#  Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x ( because a view of a tensor shares the same memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#torch.unsqeeze-- adds a single dim to a target tensor at specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute-- rearranges the dim of a target tensor in a specific order
x_original=torch.rand(size=(224,224,3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted=x_original.permute(2,0,1) #[color_channels, height, width] # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")# colour trensors height and width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]= 728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with Numpy

In [ ]:
#create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Lets index on the most inner bracket (last dimension)
x[0][1][1]

tensor(5)

In [ ]:
# you can use also use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## Pytorch tensors and numpy
Numpy is a popular scientific python numerical computing library.

And because of this , Pytorch has functionality to interact with it
* Data in numpy , want in pytorch tensor-> torch.from_numpy(ndarray)
* Pytorch tensor-> Numoy -> torch.Tensor.numpy()


In [2]:
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype

dtype('float64')

In [4]:
torch.arange(1.0,8.0).dtype

torch.float32

In [5]:
# change the value of array, what will do to "tensor"
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
# Tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
numpy_tensor.dtype

dtype('float32')

In [8]:
#change the tensor, what happens to 'numpy_tensor'
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
start with random numbers-> tensor operations -> update random numbers to try and make them better representations of the data -> again-> again-> again

To reduce the randomness in neural networks and pytorch comes the concept pf a "random seed"

Essentially what the random seed does is flavour the randomness

In [9]:
torch.rand(3,3)

tensor([[0.9148, 0.8810, 0.3385],
        [0.6433, 0.6597, 0.3069],
        [0.5715, 0.1825, 0.8088]])

In [10]:
import torch
# create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.3035, 0.9297, 0.8613, 0.1223],
        [0.2164, 0.6150, 0.4480, 0.6198],
        [0.7053, 0.8127, 0.5662, 0.8403]])
tensor([[0.4186, 0.7116, 0.1459, 0.2968],
        [0.7222, 0.9387, 0.3811, 0.6204],
        [0.0091, 0.0861, 0.9548, 0.4482]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [11]:
# lets make some random but reproducible tensors
import torch

#set the random seed
random_seed=42
torch.manual_seed(random_seed)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(random_seed)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the GPUs (and making faster computations)


### Getting a GPU

1. Easiest- use google colab for a free GPU
2. Use your own GPU
3. Use cloud computing-GCP, AWS, Azure

### 2. Check for GPU access for pytorch

In [4]:
import torch
torch.cuda.is_available()

True

In [5]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.5.1+cu121
12.1
True


In [6]:
#set up device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [8]:
import torch
print(torch.__file__)

/usr/local/lib/python3.12/dist-packages/torch/__init__.py


In [1]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.5.1+cu121
12.1
True
NVIDIA GeForce RTX 4050 Laptop GPU


## 3. Putting tensor(and models) on the GPU
The reason we want our tensors/models on the GPU is bcz using a GPU results in faster computations

In [2]:
# create atensor (default on the CPU)
tensor=torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensor to gpu if available 
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensrs back to the CPU

In [8]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [9]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')